version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mld-backend-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 
volumes:
  postgres_data:
